trigger:
- main

name: '1.1.$(DayOfYear)$(rev:rr)'

jobs:
- job: BuildApple
  pool:
    vmImage: macOS-latest
  steps:
  - checkout: self
    clean: true
    path: "TestApp"
  - task: NodeTool@0 
    inputs:
      versionSpec: '14.x'
  - script: |
      npm --version
      node --version
    displayName: 'Show NPM version'
  - script: |
      ns --version --json
    displayName: 'Show nativescript version'
