trigger:
- main

name: '1.1.$(DayOfYear)$(rev:rr)'

jobs:
- job: BuildApple
  pool:
    vmImage: macOS-latest
  steps:
  - checkout: self
    clean: true
    path: "TestApp"
  - script: |
      ns --version --json
    displayName: 'Show nativescript version'
